In [ ]:
import os
import pandas as pd
from utils.plotting import *
from utils.data import *

# Loading Cached Data

In [7]:
from utils.data import *
data = load_data(table_name="magic_gamma_telescope")

2025-03-27 01:10:03 - INFO - Fetching data from database
2025-03-27 01:10:03 - INFO - Fetching data from postgres database...
2025-03-27 01:10:03 - INFO - Caching data in parquet file...

FileNotFoundError: [Errno 2] No such file or directory: '/app:/app/data/cached_data.parquet'

In [8]:
!ls

1_eda.ipynb  2_univariate_analysis.ipynb  3_bivariate_analysis.ipynb

# Exploratory Data Analysis

In [4]:
data.shape

(19020, 11)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   fLength   19020 non-null  float64
 1   fWidth    19020 non-null  float64
 2   fSize     19020 non-null  float64
 3   fConc     19020 non-null  float64
 4   fConc1    19020 non-null  float64
 5   fAsym     19020 non-null  float64
 6   fM3Long   19020 non-null  float64
 7   fM3Trans  19020 non-null  float64
 8   fAlpha    19020 non-null  float64
 9   fDist     19020 non-null  float64
 10  target    19020 non-null  object
dtypes: float64(10), object(1)
memory usage: 1.6+ MB

In [6]:
data.columns

Index(['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long',
       'fM3Trans', 'fAlpha', 'fDist', 'target'],
      dtype='object')

In [7]:
data.describe()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist
count,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000
mean,53.250154,22.180966,2.825017,0.380327,0.214657,-4.331745,10.545545,0.249726,27.645707,193.818026
std,42.364855,18.346056,0.472599,0.182813,0.110511,59.206062,51.000118,20.827439,26.103621,74.731787
min,4.283500,0.000000,1.941300,0.013100,0.000300,-457.916100,-331.780000,-205.894700,0.000000,1.282600
25%,24.336000,11.863800,2.477100,0.235800,0.128475,-20.586550,-12.842775,-10.849375,5.547925,142.492250
50%,37.147700,17.139900,2.739600,0.354150,0.196500,4.013050,15.314100,0.666200,17.679500,191.851450
75%,70.122175,24.739475,3.101600,0.503700,0.285225,24.063700,35.837800,10.946425,45.883550,240.563825
max,334.177000,256.382000,5.323300,0.893000,0.675200,575.240700,238.321000,179.851000,90.000000,495.561000

In [9]:
data.isna().sum()

fLength     0
fWidth      0
fSize       0
fConc       0
fConc1      0
fAsym       0
fM3Long     0
fM3Trans    0
fAlpha      0
fDist       0
target      0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(115)

In [11]:
data[data.duplicated()]

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,target
12827,202.8290,73.9967,4.3622,0.0678,0.0364,-66.4079,-159.3540,-21.2584,76.1130,348.9780,h
13332,30.1721,16.8838,2.6902,0.4673,0.2704,8.8759,25.3694,14.0300,74.7090,229.2960,h
13486,69.7676,18.9821,2.7478,0.5255,0.2654,-44.5832,-30.7591,-12.9547,33.0052,303.9140,h
14150,130.3080,13.3030,2.6021,0.3250,0.1812,-204.5730,116.0500,4.7837,49.7590,173.5520,h
14160,16.9894,11.0002,2.4564,0.6294,0.3514,-3.4902,8.0823,-7.0516,55.3930,91.3761,h
...,...,...,...,...,...,...,...,...,...,...,...
18809,60.5328,34.9208,3.0436,0.2732,0.1750,-39.5703,45.4899,-28.7449,0.8124,290.6000,h
18826,38.7641,20.0218,2.6279,0.2921,0.1543,-49.9354,-21.7010,-13.0915,19.7802,136.9650,h
18831,22.2134,18.3853,2.5653,0.4354,0.2599,-16.5600,16.1254,13.1403,23.6480,93.1750,h
18929,19.8489,12.8985,2.3847,0.5567,0.3155,-12.1732,-10.7301,7.9112,55.0925,168.9720,h
19001,57.1905,35.5095,2.7177,0.2337,0.1197,-48.5112,-54.2835,32.3612,44.7320,102.9950,h